#ifndef EDITOR_CONSTANTS_H
#define EDITOR_CONSTANTS_H

// MAP CONSTANTS
#define BLOCK_SIZE 16

#define MAP_WIDTH_BLOCKS 35
#define MAP_HEIGHT_BLOCKS 20

#define MAP_WIDTH_PIXELS (MAP_WIDTH_BLOCKS * BLOCK_SIZE)
#define MAP_HEIGHT_PIXELS (MAP_HEIGHT_BLOCKS * BLOCK_SIZE)

// HITBOXES

// PLAYER
#define DUCK_HITBOX_WIDTH 12
#define DUCK_HITBOX_HEIGHT 23
#define DUCK_LAYED_HITBOX_HEIGHT (static_cast<float>(DUCK_HITBOX_HEIGHT) / 2)

// COLLECTABLE
#define COLLECTABLE_HITBOX_WIDTH 32
#define COLLECTABLE_HITBOX_HEIGHT 32

// BULLET
#define BULLET_HITBOX_WIDTH 3
#define BULLET_HITBOX_HEIGHT 3

// BOX
#define BOX_HITBOX_WIDTH 16
#define BOX_HITBOX_HEIGHT 16

// WINDOW

#define WINDOW_BLOCK_SIZE (BLOCK_SIZE * 2)

#define WINDOW_WIDTH_BLOCKS (MAP_WIDTH_BLOCKS * 2)
#define WINDOW_HEIGHT_BLOCKS (MAP_HEIGHT_BLOCKS * 2)

#define WINDOW_WIDTH_PIXELS (WINDOW_WIDTH_BLOCKS * WINDOW_BLOCK_SIZE)
#define WINDOW_HEIGHT_PIXELS (WINDOW_HEIGHT_BLOCKS * WINDOW_BLOCK_SIZE)

#define QUANTITY_BlOCKS (WINDOW_WIDTH_BLOCKS * WINDOW_HEIGHT_BLOCKS)

#endif  // EDITOR_CONSTANTS_H

